//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchAndEnjoy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anime
    {
        public string Name { get; set; }
        public string Genre { get; set; }
        public int ReleaseYear { get; set; }
        public int No_ofSeasons { get; set; }
        public int No_ofEps { get; set; }
        public Nullable<double> Rating { get; set; }
        public string Cast { get; set; }
        public Nullable<double> Price { get; set; }
        public int Id { get; set; }
    }
}
